version: 2
jobs:
  build:
    docker:
      - image: circleci/node:current
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run ESLint
          command: npm run eslint
      - run:
          name: Run Tests
          command: npm test
