version: 2
jobs:
  build:
    docker:
      - image: circleci/node:current-browsers
    steps:
      - checkout
      - run:
          name: Install awscli
          command: sudo apt-get update && sudo apt-get install -y awscli
      - run:
          name: AWS version
          command: aws --version
      - run:
          name: mkdir aws
          command: mkdir ~/.aws
      - run:
          name: check credentials
          command: printf "[default]\naws_access_key_id = ${AWS_ACCESS_KEY_ID}\naws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}\nregion=${AWS_DEFAULT_REGION}\n\n[${AWS_ROLE_NAME}]\nrole_arn = ${AWS_ROLE_ARN}\nsource_profile = default\nregion=${AWS_DEFAULT_REGION}" > ~/.aws/credentials
      - run:
          name: ls AWS credentials
          command: ls -all ~/.aws
      - run:
          name: Upload
          command: aws s3 cp dist/rci.min.js s3://rci-dev-euwest1-sdk --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers --profile ${AWS_ROLE_NAME}
#      - run:
#          name: Install Dependencies
#          command: npm install
#      - run:
#          name: Run ESLint
#          command: npm run eslint
#      - run:
#          name: Run Tests
#          command: npm test
#      - run:
#          name: Echo test
#          command: echo test
#      - run:
#          name: Ignore non checked in files
#          command: git checkout -- .
#      - run:
#          name: Show git tags
#          command: git tag -l
#      - run:
#          name: Set Github identity
#          command: git config --global user.email ${GIT_EMAIL} && git config --global user.name ${GIT_NAME}
#      - run:
#          name: Update NPM version
#          command: npm version from-git --allow-same-version
#      - run:
#          name: Authenticate with registry
#          command: node node_modules/npm-cli-login/bin/npm-cli-login.js -u ${NPM_USERNAME} -p ${NPM_PASSWORD} -e ${NPM_EMAIL}
#      - run:
#          name: Publish package
#          command: npm publish --access public
  deploy:
    docker:
      - image: cibuilds/aws:1.16.1
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run:
          name: AWS S3
          command: aws s3 sync build s3://<URL> --delete

#workflows:
#  version: 2
#  deploy:
#    jobs:
#      - build:
#          filters:
#            tags:
#              only: /.*/
#            branches:
#              ignore: /.*/


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
#          filters:
#            branches:
#              only: master